services:
  postgres:
    image: postgres:16-alpine
    container_name: lixeira-tech-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: lixeira_tech
      POSTGRES_USER: lixeira_tech
      POSTGRES_PASSWORD: lixeira_tech_dev
    ports:
      - "5432:5432"
    volumes:
      - lixeira_tech_postgres_data:/var/lib/postgresql/data

volumes:
  lixeira_tech_postgres_data:
